# Site settings
title: BY Blog
SEOTitle: NoDelay的博客 | BY Blog
header-img: img/post-bg-desk.jpg
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, NoDelay的博客, qiubaiying, NoDelay, iOS, Apple, iPhone"
url: "http://https://no-delay.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/no-delay/no-delay.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
featured-condition-size: 1     # A tag will be featured if the size of it is more than this condition value

# SNS settings
RSS: false

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页
